---

- name: install > Packages
  package:
    name:  "{{ item }}"
    state: present
    update_cache: true
## not supported on yum
#    install_recommends: false
#    cache_valid_time:   3600
  with_items:
    - pam-ssh-agent-auth
    - sudo
