---

- include: debian.yml
  when: ansible_os_family == 'Debian'

# Install
- include: install.yml
  tags:
    - manala_pam_ssh_agent_auth

# Sudo
- include: sudo.yml
  tags:
    - manala_pam_ssh_agent_auth
