---

- name: Include distribution version-specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version|int }}.yml"

# Requirements
- include: requirements.yml
  tags:
    - manala_pam_ssh_agent_auth

# Install
- include: install.yml
  tags:
    - manala_pam_ssh_agent_auth

# Sudo
- include: sudo.yml
  tags:
    - manala_pam_ssh_agent_auth
