---

- name: Requirements > Sudo package check
  ansible.builtin.package_facts:
    manager: auto

- name: Requirements > Sudo package check fail
  ansible.builtin.fail:
    msg: Package "sudo" must be installed
  when: (ansible_facts.packages['sudo'] | length) == 0
