---

- name: Install sudo config
  ansible.builtin.copy:
    dest: /etc/sudoers.d/99-pam-ssh-agent-auth
    content: |
      # This file is managed by Ansible as part of the pam-ssh-agent-auth role
      {{ pamsshagentauth_sudoers_config }}
    owner: root
    mode: ug=r,o=
    validate: /usr/sbin/visudo --check --file=%s
  notify:
    - Restart sudo

- name: Modify PAM configuration for sudo
  ansible.builtin.blockinfile:
    dest: /etc/pam.d/sudo
    insertbefore: '^@include common-auth'
    block: |
      auth {{ pamsshagentauth_pam_control }} {{ pamsshagentauth_pam_module_path }} {{ pamsshagentauth_pam_module_arguments }}
  notify:
    - Restart sudo
