---

- name: Restart sudo
  ansible.builtin.service:
    name: sudo
    state: restarted
  when: >
    not (ansible_virtualization_type is defined and (ansible_virtualization_type == "docker")) and
    not ansible_distribution == 'Ubuntu'
